# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cobject.proto\x12\x06object\"\x1e\n\rDetectRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"X\n\nObjectData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0c\n\x04\x62\x62ox\x18\x04 \x03(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\"N\n\x0e\x44\x65tectResponse\x12#\n\x07objects\x18\x01 \x03(\x0b\x32\x12.object.ObjectData\x12\x17\n\x0fprocessing_time\x18\x02 \x01(\x02\x32H\n\rObjectService\x12\x37\n\x06\x44\x65tect\x12\x15.object.DetectRequest\x1a\x16.object.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTREQUEST']._serialized_start=24
  _globals['_DETECTREQUEST']._serialized_end=54
  _globals['_OBJECTDATA']._serialized_start=56
  _globals['_OBJECTDATA']._serialized_end=144
  _globals['_DETECTRESPONSE']._serialized_start=146
  _globals['_DETECTRESPONSE']._serialized_end=224
  _globals['_OBJECTSERVICE']._serialized_start=226
  _globals['_OBJECTSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
